### ISSUE TITLE
Dear author,When I used the google-patents -Scraper

### ISSUE THREAD

**Issue by yedoudaren** [wenyalintw/Google-Patents-Scraper#1]
Dear author,When I used the google-patents -Scraper, I typed the terms and then clicked search, it was the program that flitted back and reported the error. May I ask the reason?

![Snipaste_2019-09-26_13-17-58](https://user-images.githubusercontent.com/29808495/65660087-2c866c00-e060-11e9-84c7-a3e558fe31b3.png)
我使用的ssr作代理

**Comment by wenyalintw** [comment]
Setting proxy isn't necessary, it was a bug.
I just fixed it and updated the repo, thx for your notification!
I didn't do lots of error handling, welcome to fork the repo and create a pull request, thanks!

ps. I saw your comment on youtube demo before this lol, just paste the same reply I made there so others who read this can know the progress.
